name: ${project.name}
main: com.endercrest.voidspawn.VoidSpawn
version: ${project.version}
website: ${project.url}
description: Teleports player on contact with the void.
authors: [tcvs]
softdepend: [BentoBox, uSkyBlock, SuperiorSkyblock2]
api-version: 1.21.4
commands:
    voidspawn:
        description: All commands for voidspawn
        aliases: [vs, voidspawn]
permissions:
    vs.admin.mode:
        description: Grants you the /void mode command
        default: op
    vs.admin.reload:
        description: Grants you the /void reload command
        default: op
    vs.admin.remove:
        description: Grants you the /void remove command
        default: op
    vs.admin.set:
        description: Grants you the /void set command
        default: op
    vs.admin.help:
        description: Grants you the /void help command
        default: op
    vs.admin.detector:
        description: Grants you the /void detector command
        default: op
    vs.admin.status:
        description: Grants you the /void status command
        default: op
    vs.admin.option:
        description: Grants you the /void option command
        default: op
    vs.admin.*:
        description: Grants you the /void command
        default: op
        children:
            vs.admin.set: true
            vs.admin.reload: true
            vs.admin.remove: true
            vs.admin.mode: true
            vs.admin.help: true
            vs.admin.detector: true
            vs.admin.status: true
            vs.admin.option: true
    vs.enable:
      default: true
      description: Enables teleportation for the player
    vs.*:
        description: Gives all permissions
        default: false
        children:
            vs.admin.*: true
            vs.enable: true